UNIT_OBSTACLE_SIZE = 5.
UNIT_OBSTACLE_VOLUME = UNIT_OBSTACLE_SIZE**3
UNIT_PROTECTED_ZONE_SIZE = 50

UNALLOCATED_ZONE = 0.
OBSTACLE_ZONE = 1.
PROTECTED_ZONE = 2.

LINE_SHAPE = 0
Z_SHAPE = 1
L_SHAPE = 2
INV_L_SHAPE = 3
SQUARE_SHAPE = 4
NUMBER_OF_OBSTACLE_SHAPES = 5
SINGLE_UNIT_SHAPE = 100


